export interface IProfessional {
    bairro: string,
    cep: string,
    cidade: string,
    cpf: string,
    crm: string,
    dataNascimento: string,
    email: string,
    endereco: string,
    enderecoNumero: string,
    id: string,
    nome: string,
    role: string,
    telefone: string,
  }